backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
logo_url: static/DPC.ico
media_folder: "static/images/uploads"
public_folder: "public/images/uploads"
collections:
  - name: template
    label: Posts
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: Projects
    label: Project
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Category", name: "category", widget: "text" }
      - {
          label: "Date",
          name: "date",
          date_format: "YYYY-MM-DD", # Hugo typically uses the YYYY-MM-DD format for dates
          time_format: "HH:mm:ssZ",
          widget: "datetime",
        }
      - { label: "Client", name: "client", widget: "text" }
      - { label: "Role", name: "role", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "image_caption", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "content/posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Publish Date",
          name: "date",
          date_format: "DD.MM.YYYY",
          time_format: "HH:mm",
          widget: "datetime",
        }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "image_caption", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
